// Code generated by genx:code@v0.3.8 DO NOT EDIT.
package validation

import (
	"fmt"
)

func (e Error) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[VALIDATION::ERROR:%d] unknown", e)
	case ERROR_UNDEFINED:
		return "[VALIDATION::ERROR:0] undefined"
	case ERROR__STRING_LENGTH_MODE:
		return "[VALIDATION::ERROR:1] invalid string length mode, expect 'byte' or 'rune'"
	case ERROR__NOT_MATCH_REGEXP:
		return "[VALIDATION::ERROR:2] invalid string not match regexp"
	case ERROR__SLICE_PARAM:
		return "[VALIDATION::ERROR:3] invalid string parameter"
	case ERROR__MAP_PARAM:
		return "[VALIDATION::ERROR:4] invalid map parameter"
	case ERROR__INPUT_TYPE:
		return "[VALIDATION::ERROR:5] invalid input: invalid type"
	case ERROR__INPUT_VALUE:
		return "[VALIDATION::ERROR:6] invalid input: invalid value"
	case ERROR__MISSING_REQUIRED:
		return "[VALIDATION::ERROR:7] invalid input: missing required"
	case ERROR__UNREGISTERED_RULE:
		return "[VALIDATION::ERROR:8] unregistered rule"
	case ERROR__DEC_INVALID_INPUT:
		return "[VALIDATION::ERROR:9] decoder: invalid input, expecting a pointer value"
	}
}
