// Code generated by genx:code DO NOT EDIT.
package validation

import (
	"fmt"
)

func (e Error) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[validation.Error:%d] unknown", e)
	case ERROR_UNDEFINED:
		return "[validation.Error:0] undefined"
	case ERROR__STRING_LENGTH_MODE:
		return "[validation.Error:1] invalid string length mode, expect 'byte' or 'rune'"
	case ERROR__NOT_MATCH_REGEXP:
		return "[validation.Error:2] invalid string not match regexp"
	case ERROR__SLICE_PARAM:
		return "[validation.Error:3] invalid string parameter"
	case ERROR__MAP_PARAM:
		return "[validation.Error:4] invalid map parameter"
	case ERROR__INPUT_TYPE:
		return "[validation.Error:5] invalid input: invalid type"
	case ERROR__INPUT_VALUE:
		return "[validation.Error:6] invalid input: invalid value"
	case ERROR__MISSING_REQUIRED:
		return "[validation.Error:7] invalid input: missing required"
	case ERROR__UNREGISTERED_RULE:
		return "[validation.Error:8] unregistered rule"
	case ERROR__DEC_INVALID_INPUT:
		return "[validation.Error:9] decoder: invalid input, expecting a pointer value"
	}
}
