// Code generated by genx:code@v0.3.0 DO NOT EDIT.
package rule

import (
	"fmt"
)

func (e Error) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[rule.Error:%d] unknown", e)
	case ERROR_UNDEFINED:
		return "[rule.Error:0] undefined"
	case ERROR__INVALID_RULE_LEADER:
		return "[rule.Error:1] invalid rule name leader, expect start with '@'"
	case ERROR__MISSING_RULE_NAME:
		return "[rule.Error:2] missing rule name"
	case ERROR__INVALID_PARAM_LEADER:
		return "[rule.Error:3] invalid rule parameter list leader, expect start with '<'"
	case ERROR__INVALID_PARAM_TAILER:
		return "[rule.Error:4] invalid rule parameter list tailer, expect end with '>'"
	case ERROR__INVALID_PARAMS:
		return "[rule.Error:5] invalid rule parameter list content"
	case ERROR__INVALID_RANGE_LEADER:
		return "[rule.Error:6] invalid rule range leader, expect start with '[' or '('"
	case ERROR__INVALID_RANGE_TAILER:
		return "[rule.Error:7] invalid rule range tailer, expect end with ']' or ')'"
	case ERROR__INVALID_RANGE_COUNT:
		return "[rule.Error:8] invalid rule range count, expect 1 or 2"
	case ERROR__INVALID_RANGE_MODE:
		return "[rule.Error:9] invalid rule range mode, while length mode must be quoted with '[]'"
	case ERROR__INVALID_VALUE_LEADER:
		return "[rule.Error:10] invalid rule value leader, expect start with '{'"
	case ERROR__INVALID_VALUE_TAILER:
		return "[rule.Error:11] invalid rule value tailer, expect end with '}'"
	case ERROR__INVALID_REGEXP_LEADER:
		return "[rule.Error:12] invalid rule matcher leader, expect start with '/'"
	case ERROR__INVALID_REGEXP_TAILER:
		return "[rule.Error:13] invalid rule matcher leader, expect end with '/'"
	case ERROR__FAILED_COMPILE_REGEXP:
		return "[rule.Error:14] failed to compile regexp"
	case ERROR__INVALID_QUOTED_DEFAULT_TAILER:
		return "[rule.Error:15] invalid rule quoted default value tailer, expect quoted with `'`"
	case ERROR__INVALID_LITERAL:
		return "[rule.Error:16] invalid rule literal"
	}
}
