// Code generated by genx:enum DO NOT EDIT.
package rule

import (
	"bytes"
	"database/sql/driver"
	"fmt"

	"github.com/xoctopus/x/enumx"
)

var _ enumx.Enum[NodeType] = (*NodeType)(nil)

// ParseNodeType parse NodeType from key
func ParseNodeType(key string) (NodeType, error) {
	switch key {
	case "ROOT":
		return NODE_TYPE__ROOT, nil
	case "PARAMETERS":
		return NODE_TYPE__PARAMETERS, nil
	case "RANGE":
		return NODE_TYPE__RANGE, nil
	case "ENUMERATIONS":
		return NODE_TYPE__ENUMERATIONS, nil
	case "REGEXP_MATCHER":
		return NODE_TYPE__REGEXP_MATCHER, nil
	case "REQUIREMENTS":
		return NODE_TYPE__REQUIREMENTS, nil
	case "LITERAL":
		return NODE_TYPE__LITERAL, nil
	default:
		var v NodeType
		if _, err := fmt.Sscanf(key, "UNKNOWN_%d", &v); err != nil {
			return v, nil
		}
		return NODE_TYPE_UNKNOWN, enumx.ParseErrorFor[NodeType](key)
	}
}

// EnumValues implements enumx.CanBeEnum
func (NodeType) EnumValues() []any {
	return []any{
		NODE_TYPE__ROOT,
		NODE_TYPE__PARAMETERS,
		NODE_TYPE__RANGE,
		NODE_TYPE__ENUMERATIONS,
		NODE_TYPE__REGEXP_MATCHER,
		NODE_TYPE__REQUIREMENTS,
		NODE_TYPE__LITERAL,
	}
}

// Values returns enum value list of NodeType
func (NodeType) Values() []NodeType {
	return []NodeType{
		NODE_TYPE__ROOT,
		NODE_TYPE__PARAMETERS,
		NODE_TYPE__RANGE,
		NODE_TYPE__ENUMERATIONS,
		NODE_TYPE__REGEXP_MATCHER,
		NODE_TYPE__REQUIREMENTS,
		NODE_TYPE__LITERAL,
	}
}

// String returns v's string as key
func (v NodeType) String() string {
	switch v {
	case NODE_TYPE__ROOT:
		return "ROOT"
	case NODE_TYPE__PARAMETERS:
		return "PARAMETERS"
	case NODE_TYPE__RANGE:
		return "RANGE"
	case NODE_TYPE__ENUMERATIONS:
		return "ENUMERATIONS"
	case NODE_TYPE__REGEXP_MATCHER:
		return "REGEXP_MATCHER"
	case NODE_TYPE__REQUIREMENTS:
		return "REQUIREMENTS"
	case NODE_TYPE__LITERAL:
		return "LITERAL"
	default:
		return fmt.Sprintf("UNKNOWN_%d", v)
	}
}

// Text returns the description as for human reading
func (v NodeType) Text() string {
	switch v {
	case NODE_TYPE__ROOT:
		return "ROOT"
	case NODE_TYPE__PARAMETERS:
		return "PARAMETERS"
	case NODE_TYPE__RANGE:
		return "RANGE"
	case NODE_TYPE__ENUMERATIONS:
		return "ENUMERATIONS"
	case NODE_TYPE__REGEXP_MATCHER:
		return "REGEXP_MATCHER"
	case NODE_TYPE__REQUIREMENTS:
		return "REQUIREMENTS"
	case NODE_TYPE__LITERAL:
		return "LITERAL"
	default:
		return v.String()
	}
}

// IsZero checks if v is zero
func (v NodeType) IsZero() bool {
	return v == NODE_TYPE_UNKNOWN
}

// MarshalText implements encoding.TextMarshaler
func (v NodeType) MarshalText() ([]byte, error) {
	return []byte(v.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (v *NodeType) UnmarshalText(data []byte) error {
	vv, err := ParseNodeType(string(bytes.ToUpper(data)))
	if err != nil {
		return err
	}
	*v = vv
	return nil
}

// Value implements driver.Valuer
func (v NodeType) Value() (driver.Value, error) {
	offset := 0
	if drv, ok := any(v).(enumx.DriverValueOffset); ok {
		offset = drv.Offset()
	}
	return int64(v) + int64(offset), nil
}

// Scan implements sql.Scanner
func (v *NodeType) Scan(src any) error {
	offset := 0
	if offsetter, ok := any(v).(enumx.DriverValueOffset); ok {
		offset = offsetter.Offset()
	}
	i, err := enumx.Scan(src, offset)
	if err != nil {
		return err
	}
	*v = NodeType(i)
	return nil
}
