// Code generated by genx:code@v0.3.0 DO NOT EDIT.
package confhttp

import (
	"fmt"
)

func (e Error) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[confhttp.Error:%d] unknown", e)
	case ERROR_UNDEFINED:
		return "[confhttp.Error:0] undefined"
	case ERROR__HOST_ALIAS_INVALID_INPUT:
		return "[confhttp.Error:1] HOST_ALIAS_INVALID_INPUT"
	case ERROR__HOST_ALIAS_INVALID_IPV6_ADDR:
		return "[confhttp.Error:2] HOST_ALIAS_INVALID_IPV6_ADDR"
	}
}
