// Code generated by genx:code@v0.3.8 DO NOT EDIT.
package confhttp

import (
	"fmt"
)

func (e Error) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[CONFHTTP::ERROR:%d] unknown", e)
	case ERROR_UNDEFINED:
		return "[CONFHTTP::ERROR:0] undefined"
	case ERROR__HOST_ALIAS_INVALID_INPUT:
		return "[CONFHTTP::ERROR:1] HOST_ALIAS_INVALID_INPUT"
	case ERROR__HOST_ALIAS_INVALID_IPV6_ADDR:
		return "[CONFHTTP::ERROR:2] HOST_ALIAS_INVALID_IPV6_ADDR"
	}
}
