// Code generated by genx:code DO NOT EDIT.
package va

import (
	"fmt"
)

func (e Error) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[va.Error:%d] unknown", e)
	case ERROR_UNDEFINED:
		return "[va.Error:0] undefined"
	case ERROR__INVALID_LENGTH_RANGE:
		return "[va.Error:1] invalid length range, expect 1 or 2 uint values"
	case ERROR__OUT_OF_LENGTH:
		return "[va.Error:2] input value out of length limitation"
	case ERROR__INVALID_VALUE_RANGE:
		return "[va.Error:3] invalid range value"
	case ERROR__OUT_OF_VALUE_RANGE:
		return "[va.Error:4] input value out of value range"
	case ERROR__INVALID_ENUM:
		return "[va.Error:5] invalid enumeration value"
	case ERROR__OUT_OF_ENUMERATED_VALUES:
		return "[va.Error:6] input value out of enumerated values"
	case ERROR__INVALID_MULTIPLE:
		return "[va.Error:7] invalid multiple"
	case ERROR__NOT_MATCH_MULTIPLE:
		return "[va.Error:8] input value not match multiple"
	case ERROR__INVALID_FLOAT_SCALE:
		return "[va.Error:9] invalid float scale, expect most 2 uint max 31"
	case ERROR__OUT_OF_FLOAT_SCALE:
		return "[va.Error:10] input value out of float scale"
	case ERROR__INVALID_INT_BITS:
		return "[va.Error:11] invalid int bits, expect most 1 uint max 64"
	case ERROR__OUT_OF_INT_BITS:
		return "[va.Error:12] input value out of int bits"
	case ERROR__NOT_MATCH_REGEXP:
		return "[va.Error:13] input value not match regexp"
	case ERROR__INVALID_INT_VALUE:
		return "[va.Error:14] invalid input, expect int64/uint64"
	}
}
