// Code generated by genx:code@v0.3.8 DO NOT EDIT.
package va

import (
	"fmt"
)

func (e Error) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[VA::ERROR:%d] unknown", e)
	case ERROR_UNDEFINED:
		return "[VA::ERROR:0] undefined"
	case ERROR__INVALID_LENGTH_RANGE:
		return "[VA::ERROR:1] invalid length range, expect 1 or 2 uint values"
	case ERROR__OUT_OF_LENGTH:
		return "[VA::ERROR:2] input value out of length limitation"
	case ERROR__INVALID_VALUE_RANGE:
		return "[VA::ERROR:3] invalid range value"
	case ERROR__OUT_OF_VALUE_RANGE:
		return "[VA::ERROR:4] input value out of value range"
	case ERROR__INVALID_ENUM:
		return "[VA::ERROR:5] invalid enumeration value"
	case ERROR__OUT_OF_ENUMERATED_VALUES:
		return "[VA::ERROR:6] input value out of enumerated values"
	case ERROR__INVALID_MULTIPLE:
		return "[VA::ERROR:7] invalid multiple"
	case ERROR__NOT_MATCH_MULTIPLE:
		return "[VA::ERROR:8] input value not match multiple"
	case ERROR__INVALID_FLOAT_SCALE:
		return "[VA::ERROR:9] invalid float scale, expect most 2 uint max 31"
	case ERROR__OUT_OF_FLOAT_SCALE:
		return "[VA::ERROR:10] input value out of float scale"
	case ERROR__INVALID_INT_BITS:
		return "[VA::ERROR:11] invalid int bits, expect most 1 uint max 64"
	case ERROR__OUT_OF_INT_BITS:
		return "[VA::ERROR:12] input value out of int bits"
	case ERROR__NOT_MATCH_REGEXP:
		return "[VA::ERROR:13] input value not match regexp"
	case ERROR__INVALID_INT_VALUE:
		return "[VA::ERROR:14] invalid input, expect int64/uint64"
	}
}
